name: "Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v6
        with:
          name: npmlock2nix
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-shell --run "nixpkgs-fmt --check ."
      - run: ./test.sh
