name: "Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v10
      - run: |
          nix-shell --run "nixpkgs-fmt --check ."
          ./test.sh
